import React from "react";

export const langs = {
    tr: {
        //signin
        ad: 'İsim',
        soyad: 'Soyisim',
        giris: 'HAYDİ KAYDOL !',
        hosgeldin: 'Sayfamıza Hoşgeldiniz',
        kayıtol: 'Kayıt ol',
        checkbox: 'Beni hatırla',
        input5:'Lütfen adınızı giriniz!',
        input6:'Lütfen soyadınızı giriniz!',
        //homepage
        homePageGiris: "InTeritance'a ",
        homePageGiris1: "Hoş geldiniz  ",
        need: 'Neye ihtiyacınız var',
        appInfo: 'InTeritance çocuğunuzun büyümesine eşlik edecek bir birikim uygulamasıdır. InTeritance size sunduğu esnek fonksiyonlarla çocuğunuzun hayattaki dönüm noktalarına destek olabilir , geleceğini şekillendirebilirsiniz.',
        first: 'Bir',
        first__: 'cüzdanınız olması gerekir.',
        first_: 'Bir metamask hesabınız yoksa,',
        second: 'Cüzdanınızda belirli bir miktar',
        second_: 'olmalıdır.',
        third: 'Çocuklarınızın hesaplarını oluşturun ve ayarlayın.',
        fourth: 'Çocuklarınızın hesaplarını dilediğiniz gibi yönetebilir, dilediğiniz kadar yatırım yapabilirsiniz.',
        fifth: 'Belirlediğiniz tarih geldiğinde çocuğunuz cüzdanına erişebilecek.',
        loginwm: ' Metamask ile giriş yap',
        dildesgis: 'Dil değiştir',
        clickhere: 'Buraya tıklayın.',
        hakkımızda:'Hakkımızda',
        //childedit
        erisimTarihi: 'Erişim Tarihi',
        walletAdres: 'Çocuğun cüzdan adresi',
        kaydet: 'Kaydet',
        degistir: 'Değiştir',
        childeditbutton: 'Geri çek(çocuk)',
        input1:'Lütfen çocuğunuzun adını giriniz! ',
        input2:'Lütfen bir tarih seçiniz!',
        input3:'Lütfen çocuğunuzun cüzdan adresini giriniz!',
        input4:'Cüzdan adresi en az 42 karakter olmalıdır!',
        //childpage
        user: 'Hoşgeldiniz',
        geriCek: 'Parayı geri çek',
        tumParayıCek: 'Tüm parayı çek',
        miktar: 'Çekilecek miktarı giriniz.',
        tarih:'Paranızın erişime açılacağı tarih',
        //parentpage
        cocukekle: 'Çocuk ekle',
        cocuksil: 'Çocuk sil',
        send: 'Gönder',
        yourWallet: 'Senin cüzdanın',
        withdraweth : 'Ethereumu geri çek',
        sendeth: 'Ethereum gönder',
        withdrawback : 'Geri çek',
        para: 'Mevcut Para(ETH)',
        gönderilen: 'Gönderilen Miktar(ETH)',
        tutar: 'Gönderilecek / Çekilecek Tutar',
        adres: 'Cüzdan Adresi',
        //ethprice
        ethprice: 'Ethereum Fiyatı',
        block: 'Blok gezgininde görüntüle',
        error : 'Lütfen Metamask uzantısını kurunuz.',
        error2 : 'Tüm alanları doldurunuz.',
        loading:'YÜKLENİYOR...',
        errorOccured: 'HATA OLUŞTU!',
        childAdding: 'Çocuk Ekleniyor...',
        addingParent: 'Kayıt işlemi yapılıyor...',
        withdrawalProcess: 'Para çekme işlemi gerçekleşiyor...',
        vazgec: 'Vazgeç',
        vizyon: 'Ebeveynlerin çocuklarının geleceği için daha güvenilir, yeni çağa uygun ve sürdürülebilir bir sistemde kripto varlıklarını miras bırakabilecekleri uygulamalar arasında akla ilk gelen olmak.',
        misyon : 'Yarınlarımızı emanet edeceğimiz çocuklarımız için onların yaşamlarını kolaylaştırmak, yeni çağda yeni teknolojilerle birlikte onlara daha çağa uygun bir gelecek yaratmak amacıyla ailelerinin güvenilir bir şekilde yatırım yapabilmelerini sağlamak.',
        vizyonvemisyon : 'Vizyonumuz ve Misyonumuz',
        why : 'Neden InTeritance ?',
        p1 :' Teknoloji çağına ayak uyduran, yeni nesil bir yatırım uygulaması',
        p2 : ' Birden fazla işlem aynı sayfa üzerinde hızlı bir şekilde gerçekleştirilebilir.',
        p3 : 'Kullanıcı dostu uygulama tasarımı',
        p4 : ' Son derece güvenli',
        p5 : ' Ebeveynler hem kendilerinin hem çocuklarının kripto varlıklarını yönetebilir.',
        p6 : ' Çocukların hesaplarına erişim tarihleri gelene kadar tüm yetki ebeveynlerinde olur.',
        ourvision: 'Vizyonumuz',
        ourmission : 'Misyonumuz',
        team : 'Ekibimiz',
        bcteam : 'Blockchain ekip üyesi',
        onyuz : 'Ön yüz ekip üyesi',
        analist : 'İş analisti',
        po : 'Ürün sahibi',
        agile : 'Agile koç',
        select: 'Lütfen kullanmak istediğiniz hesabı seçiniz',
        account1: 'Interitance Hesabım',
        account2: 'Metamask Cüzdanım',
        toaccount1: 'Interitance Hesabıma Aktar',
        toaccount2: 'Metamask Cüzdanıma Aktar',
        transfer: 'Transfer gerçekleşiyor...',
        changeDate: 'Tarih güncelleniyor...',
        close: 'Kapat'
    },

    en: {
        //signin
        ad: 'Name',
        soyad: 'Surname',
        giris: 'LETS SIGN YOU UP',
        hosgeldin: 'Welcome to our page',
        kayıtol: 'Sign Up',
        checkbox: 'Keep me logged in',
        input5:'Please input your name!',
        input6:'Please input your surname!',
        //homepage
        homePageGiris: ' InTeritance ',
        homePageGiris1: 'Welcome  ',
        need: 'What do you need',
        appInfo: 'InTeritance is a saving app that accompanies your childs growth.  You can support your children’s milestones with the flexible functions our app offers you and shape your children’s future',
        first: 'You need to have a ',
        first__: 'wallet.',
        first_: "If you don't have a metamask account, ",
        second: 'You must have a certain amount of',
        second_: 'in your wallet.',
        third: "Create and set up your children's accounts.",
        fourth: 'You can manage your children’s accounts as you wish and invest as much as you want.',
        fifth: 'When the date you set comes, your child will have access to their wallet.',
        loginwm: 'Login with Metamask',
        dildesgis: 'Change language',
        clickhere: 'Click here.',
        hakkımızda:'About us',
        //childedit
        erisimTarihi: 'Date of Access',
        walletAdres: 'Wallet address of the child',
        kaydet: 'Save',
        degistir: 'Change',
        childeditbutton: 'Withdraw(Child)',
        input1:'Please input your child name! ',
        input2:'Please select a date!',
        input3:'Please input your child wallet address!',
        input4: 'Wallet address must be minimum 42 characters!',
        //childpage
        user: 'Welcome',
        geriCek: 'Withdraw money',
        tumParayıCek: 'Withdraw all money',
        miktar:'Enter the amount of to withdraw',
        tarih: 'Your money will be accessible on',
        //parentpage
        cocukekle: 'Add child',
        cocuksil: 'Delete child',
        send: 'Send',
        money: 'Current amonunt of money',
        yourWallet: 'Your wallet',
        withdraweth : 'Withdraw Ethereum',
        sendeth: 'Send ethereum',
        withdrawback : 'Withdraw Back',
        para: 'Current Money(ETH)',
        gönderilen: 'Total Given(ETH)',
        tutar: 'Amount To Be Sent / Withdrawn',
        adres: 'Wallet Address',
        ethprice: 'Ethereum Price',
        block: 'View in block explorer',
        error : 'Please install Metamask extensions',
        error2 : 'Please fill all the fields',
        loading:'LOADING...',
        errorOccured: 'ERROR OCCURED!',
        childAdding: 'Child is adding...',
        addingParent: 'Registration in progress...',
        withdrawalProcess: 'Withdrawal is in progress...',
        vazgec: 'Cancel',
        ourvision: 'Our Vision',
        ourmission : 'Our Mission',
        vizyon: 'To be the first to come to mind among the applications where parents can hand their crypto assets down in a more reliable, avant-garde and sustainable system for the future of their children.',
        misyon : 'To ease the lives of children to whom we will entrust our future and to provide that families can invest to create a future in tune with the times for their children in a more reliable way with new technologies in the new era.',
        vizyonvemisyon : 'Our Vision and Our Mission',
        why : 'Why InTeritance ?',
        p1 :' A new generation investment application that keeps up with the era of technology',
        p2 : 'More than one transaction can be carried out swiftly on one page at the same time.',
        p3 : 'User-friendly application design',
        p4 : 'Extremely safe',
        p5 : 'Parents can manage both their and their children’s crypto assets.',
        p6 : 'Parents have all authorization until the date of children’s access to their accounts comes.',
        team : 'Our Team',
        bcteam : 'Blockchain team member',
        onyuz : 'Frontend team member',
        analist : 'Business analyst',
        po : 'Product owner',
        agile : 'Agile coach',
        select:'Please select the account you want to use',
        account1: 'Interitance Account',
        account2: 'Metamask Wallet',
        toaccount1: 'Trasanfer to my Interitance Account',
        toaccount2: 'Transfer to my Metamask Wallet',
        transfer: 'Transfer in progress...',
        changeDate: 'Updating date... ',
        close: 'Close',
    }
}

const LangContext = React.createContext(langs.tr);
export default LangContext;